services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Exposing React app on port 3000
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000
      - VITE_TRPC_ROUTE=trpc
    volumes:
      - ./frontend/app:/app  # For live development
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'  # Exposing backend on port 4000
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mydatabase
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend/src:/app  # For live development
      - /app/node_modules

  # Redis Service (For caching)
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  # Postgres Service (Database)
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'  # Exposing Postgres on port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent volume for data storage

volumes:
  postgres-data:
  node_modules:
